config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    match '/users/finish_signup' => 'users/confirmations#finish_signup', via: [:get, :patch], as: :finish_signup
  end

  devise_for :users, path: 'users', controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions:           'users/sessions',
    registrations:      'users/registrations',
    passwords:          'users/passwords',
    confirmations:      'users/confirmations',
  }

  # translated routes by the route_translator gem
  localized do

    resources :trips, except: [:index, :destroy] do
      member do
        get 'confirm'
        get 'delete'
        get 'resend_confirmation_email'
        get 'resend_information_email'
        get 'new_from_copy'
        get 'new_for_back'
        get 'points'
        get 'phone_number_image'
        get 'confirm_delete'
      end
      resource :phone, only: :show, controller: 'trips/phones'
      resources :messages
    end
    get 'search', to: 'search#index'
    get 'profile', to: 'profile#show', as: 'profile'
    get 'profile/trips', to: 'profile#trips', as: 'profile_trips'
    get 'profile/alerts', to: 'profile#alerts', as: 'profile_alerts'
    get 'profile/edit', to: 'profile#edit', as: 'edit_profile'
    patch 'profile', to: 'profile#update'

    get "/covoits/:from-:to", to: 'landing#index'
    # get "/covoits/:from", to: 'landing#index'
    resources :user_alerts, except: [:index]
  end

  resources :cities, defaults: { format: :json } do
    collection do
      get 'autocomplete'
      get 'main'
    end
  end

  namespace :admin do
    resources :users do
      put :lock
      delete :lock, to: 'users#unlock'
      post :send_reset_password_mail
      post :send_confirmation_mail
    end
    resources :page_parts
    resources :pages
    resources :stats, only: :index do
      collection do
        get 'trips_count'
        get 'trips_tab'
      end
    end
    root to: 'pages#index'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get "/:id", to: 'pages#show'

  root to: 'home#index'
end

app/views/admin/pages/_form.html.haml
- url = @page.new_record? ? admin_pages_path : admin_page_path(@page)
- method = @page.new_record? ? :post : :put


.well
  = simple_form_for @page, as: :page, url: url, method: method do |f|
    .row
      .col-md-6
        = f.input :name
        = f.input :slug
        = f.input :title
        = f.input :meta_desc
      .col-md-6
        = f.input :body, input_html: { rows: 24, value: f.object.body&.gsub(/\n/, '') }

    .pull-right
      = link_to 'Annuler', admin_pages_path, class: 'btn btn-default'
      = f.button :submit, class: 'btn-primary'
    .clearfix

app/views/admin/pages/edit.html.haml
%h1 Édition de la Page

= render 'form'

app/views/admin/pages/index.html.haml
%h1.pull-left Liste des Pages

= link_to 'Nouvelle page', new_admin_page_path, class: 'btn btn-primary pull-right top-list-button'

%table.table
  %tr
    %th Id
    %th Nom
    %th Titre
    %th Desc
    %th{ colspan: 2 }
  - @pages.each do |page|
    %tr
      %td= page.id
      %td= page.name
      %td= page.title
      %td= page.meta_desc
      %td= link_to 'Edit', edit_admin_page_path(page), class: 'btn btn-default btn-sm'

app/views/admin/pages/new.html.haml
%h1 Nouvelle Page

= render 'form'