config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    match '/users/finish_signup' => 'users/confirmations#finish_signup', via: [:get, :patch], as: :finish_signup
  end

  devise_for :users, path: 'users', controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions:           'users/sessions',
    registrations:      'users/registrations',
    passwords:          'users/passwords',
    confirmations:      'users/confirmations',
  }

  # translated routes by the route_translator gem
  localized do

    resources :trips, except: [:index, :destroy] do
      member do
        get 'confirm'
        get 'delete'
        get 'resend_confirmation_email'
        get 'resend_information_email'
        get 'new_from_copy'
        get 'new_for_back'
        get 'points'
        get 'phone_number_image'
        get 'confirm_delete'
      end
      resource :phone, only: :show, controller: 'trips/phones'
      resources :messages
    end
    get 'search', to: 'search#index'
    get 'profile', to: 'profile#show', as: 'profile'
    get 'profile/trips', to: 'profile#trips', as: 'profile_trips'
    get 'profile/alerts', to: 'profile#alerts', as: 'profile_alerts'
    get 'profile/edit', to: 'profile#edit', as: 'edit_profile'
    patch 'profile', to: 'profile#update'

    get "/covoits/:from-:to", to: 'landing#index'
    # get "/covoits/:from", to: 'landing#index'
    resources :user_alerts, except: [:index]
  end

  resources :cities, defaults: { format: :json } do
    collection do
      get 'autocomplete'
      get 'main'
    end
  end

  namespace :admin do
    resources :users do
      put :lock
      delete :lock, to: 'users#unlock'
      post :send_reset_password_mail
      post :send_confirmation_mail
    end
    resources :page_parts
    resources :pages
    resources :stats, only: :index do
      collection do
        get 'trips_count'
        get 'trips_tab'
      end
    end
    root to: 'pages#index'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get "/:id", to: 'pages#show'

  root to: 'home#index'
end

app/models/concerns/trips/search.rb
module Trips
  module Search
    extend ActiveSupport::Concern

    included do
      DEFAULT_SEARCH_AROUND_DISTANCE_IN_METERS = 25_000
      MAX_SEARCH_AROUND_DISTANCE_IN_METERS = 50_000
    end

    class_methods do

      def auto_around_distance(from_lon, from_lat, to_lon, to_lat)
        form_point = RGeo::Geographic.simple_mercator_factory.point(from_lat, from_lon)
        to_point = RGeo::Geographic.simple_mercator_factory.point(to_lat, to_lon)
        form_point.distance(to_point).to_f / 6
      end

      def from_to(from_lon, from_lat, to_lon, to_lat,
                  from_around_distance = DEFAULT_SEARCH_AROUND_DISTANCE_IN_METERS,
                  to_around_distance = DEFAULT_SEARCH_AROUND_DISTANCE_IN_METERS)
        around_distance = auto_around_distance(from_lon, from_lat, to_lon, to_lat)
        from_around_distance ||= around_distance
        from_around_distance = [
          from_around_distance || DEFAULT_SEARCH_AROUND_DISTANCE_IN_METERS,
          MAX_SEARCH_AROUND_DISTANCE_IN_METERS
        ].min
        to_around_distance ||= around_distance
        to_around_distance = [
          to_around_distance || DEFAULT_SEARCH_AROUND_DISTANCE_IN_METERS,
          MAX_SEARCH_AROUND_DISTANCE_IN_METERS
        ].min

        # Avoid Trips doublon
        matching_points = Point.select("DISTINCT ON (point_a.trip_id) point_a.*,
          point_a.id as point_a_id, point_a.price as point_a_price,
          point_b.id as point_b_id, point_b.price as point_b_price,

          (ST_Distance(
            ST_GeographyFromText('SRID=4326;POINT(' || point_a.lon || ' ' || point_a.lat || ')'),
            ST_GeographyFromText('SRID=4326;POINT(#{from_lon.to_f} #{from_lat.to_f})')
          ) + ST_Distance(
            ST_GeographyFromText('SRID=4326;POINT(' || point_b.lon || ' ' || point_b.lat || ')'),
            ST_GeographyFromText('SRID=4326;POINT(#{to_lon.to_f} #{to_lat.to_f})')
          )) AS point_ab_distance").
        from('points AS point_a').
        joins('INNER JOIN points AS point_b ON point_b.trip_id = point_a.trip_id').
        where("ST_Dwithin(
               ST_GeographyFromText('SRID=4326;POINT(' || point_a.lon || ' ' || point_a.lat || ')'),
               ST_GeographyFromText('SRID=4326;POINT(? ?)'),
               #{from_around_distance})", from_lon.to_f, from_lat.to_f).
        where("ST_Dwithin(
               ST_GeographyFromText('SRID=4326;POINT(' || point_b.lon || ' ' || point_b.lat || ')'),
               ST_GeographyFromText('SRID=4326;POINT(? ?)'),
               #{to_around_distance})", to_lon.to_f, to_lat.to_f).
        where('point_a.rank < point_b.rank').
        order('point_a.trip_id ASC, point_ab_distance ASC')

        select('trips.*,
          point_a_id, point_a_price,
          point_b_id, point_b_price,
          trips.id'). # trips.id is necessary here for the COUNT_COLUMN method used by Kaminari counting.
        joins("INNER JOIN (#{matching_points.to_sql}) AS point_a ON trips.id = point_a.trip_id")
      end

      def from_only(from_lon, from_lat, from_around_distance = DEFAULT_SEARCH_AROUND_DISTANCE_IN_METERS)
        from_around_distance = [
          from_around_distance || DEFAULT_SEARCH_AROUND_DISTANCE_IN_METERS,
          MAX_SEARCH_AROUND_DISTANCE_IN_METERS
        ].min

        # Avoid Trips doublon
        matching_points = Point.select("DISTINCT ON (point_a.trip_id) point_a.*,
          point_a.id AS point_a_id, point_a.price AS point_a_price,
          ST_Distance(
            ST_GeographyFromText('SRID=4326;POINT(' || point_a.lon || ' ' || point_a.lat || ')'),
            ST_GeographyFromText('SRID=4326;POINT(#{from_lon.to_f} #{from_lat.to_f})')
          ) AS point_a_distance")
        .from('points AS point_a')
        .where("ST_Dwithin(
          ST_GeographyFromText('SRID=4326;POINT(' || point_a.lon || ' ' || point_a.lat || ')'),
          ST_GeographyFromText('SRID=4326;POINT(? ?)'),
          #{from_around_distance}
        )", from_lon.to_f, from_lat.to_f)
        .where("point_a.kind <> 'To'")
        .order('point_a.trip_id ASC, point_a_distance ASC')

        select('trips.*,
          point_a_id, point_a_price, point_a_distance,
          trips.id'). # trips.id is necessary here for the COUNT_COLUMN method used by Kaminari counting.
        joins("INNER JOIN (#{matching_points.to_sql}) AS point_a ON trips.id = point_a.trip_id")
      end

      def to_only(to_lon, to_lat, to_around_distance = DEFAULT_SEARCH_AROUND_DISTANCE_IN_METERS)
        to_around_distance = [
          to_around_distance || DEFAULT_SEARCH_AROUND_DISTANCE_IN_METERS,
          MAX_SEARCH_AROUND_DISTANCE_IN_METERS
        ].min

        # Avoid Trips doublon
        matching_points = Point.select("DISTINCT ON (point_b.trip_id) point_b.*,
          point_b.id AS point_b_id, point_b.price AS point_b_price,
          ST_Distance(
            ST_GeographyFromText('SRID=4326;POINT(' || point_b.lon || ' ' || point_b.lat || ')'),
            ST_GeographyFromText('SRID=4326;POINT(#{to_lon.to_f} #{to_lat.to_f})')
          ) AS point_b_distance")
        .from('points AS point_b')
        .where("ST_Dwithin(
          ST_GeographyFromText('SRID=4326;POINT(' || point_b.lon || ' ' || point_b.lat || ')'),
          ST_GeographyFromText('SRID=4326;POINT(? ?)'),
          #{to_around_distance}
        )", to_lon.to_f, to_lat.to_f)
        .where("point_b.kind <> 'From'")
        .order('point_b.trip_id ASC, point_b_distance ASC')

        select('trips.*,
          point_b_id, point_b_price, point_b_distance,
          trips.id'). # trips.id is necessary here for the COUNT_COLUMN method used by Kaminari counting.
        joins("INNER JOIN (#{matching_points.to_sql}) AS point_b ON trips.id = point_b.trip_id")
      end

    end

  end
end

app/models/search.rb
# coding: utf-8
class Search
  include ActiveModel::Model

  attr_accessor(
    :from_city,
    :from_lon,
    :from_lat,
    :from_dist,
    :to_city,
    :to_lon,
    :to_lat,
    :to_dist,
    :date
  )


  validate :dont_search_the_past
  validate :do_select_a_city_in_the_list

  def date_value
    # dans le @search : '%d/%m/%Y'
    # date en texte de type : "vendredi 13 mai 2011" : 4 chiffres -> l'année ; 1 ou 2 chiffres -> le jour ; le mois en lettres est dans I18n.t('date.month_names'), .index("mois en lettres") donne le mois en chiffres
    #begin
    #Date.strptime(self.date, '%d/%m/%Y')
    begin
      the_day_name_in_text, the_day_number_in_text, the_month_in_text, the_year_in_text = self.date.split(/ +/)
      the_day_in_digits = Integer(the_day_number_in_text)
      the_year_in_digits = Integer(the_year_in_text)
      the_month_in_digits = I18n.t('date.month_names').index(the_month_in_text.downcase)
      Date.new(the_year_in_digits, the_month_in_digits, the_day_in_digits)
    rescue
      Date.today
    end
  end

  private

    def dont_search_the_past
      @date = I18n.localize(Date.today, :format => '%A %d %B %Y') if @date.blank?
      if self.date_value < Date.today
        #errors.add(:date, "Cherchez une date future")
        @date = I18n.localize(Date.today, :format => '%A %d %B %Y')
      end
    end

    def do_select_a_city_in_the_list
      if @from_city.present? && @from_lon.blank?
        errors.add(:from_city, "Selectionnez une ville *dans* la liste")
      end
      if @to_city.present? && @to_lon.blank?
        errors.add(:to_city, "Selectionnez une ville *dans* la liste")
      end
    end

end

app/controllers/search_controller.rb
# coding: utf-8
class SearchController < ApplicationController
  
  THE_NUMBER_OF_TRIPS_PER_PAGE = 10
  THE_NUMBER_OF_DAYS_IN_A_MONTH = 31
  THE_NUMBER_OF_DAYS_AROUND_THE_REQUESTED_DAY = 8

  def index
    load_index_meta_data

    @trips ||= []
    @search = Search.new(search_params)
    the_first_date = [(@search.date_value) -THE_NUMBER_OF_DAYS_IN_A_MONTH, (Date.today) -THE_NUMBER_OF_DAYS_IN_A_MONTH].min # we need trips of the past month to say "hey there was some trips last month" if no results
    the_last_date =  (@search.date_value) +THE_NUMBER_OF_DAYS_IN_A_MONTH

    if @search.valid?
      if @search.from_lon.present? && @search.to_lon.present?
        the_trips_around_the_requested_day = Trip
                   .unscoped
                   .includes(:points)
                   .where('departure_date >= ?', the_first_date)
                   .where('departure_date <= ?', the_last_date)
                   .where(state: 'confirmed')
                   .from_to(
                      @search.from_lon, @search.from_lat,
                      @search.to_lon, @search.to_lat,
                      @search.from_dist, @search.to_dist
                    )
                   .order(departure_date: :asc)
                   .order(departure_time: :asc)
                   #.page(params[:page]).per(THE_NUMBER_OF_TRIPS_PER_PAGE)
      elsif @search.from_lon.present?
        the_trips_around_the_requested_day = Trip
                   .unscoped
                   .includes(:points)
                   .where('departure_date >= ?', the_first_date)
                   .where('departure_date <= ?', the_last_date)
                   .where(state: 'confirmed')
                   .from_only(
                      @search.from_lon, @search.from_lat,
                      @search.from_dist
                    )
                   .order(departure_date: :asc)
                   .order(departure_time: :asc)
                   #.page(params[:page]).per(THE_NUMBER_OF_TRIPS_PER_PAGE)
      elsif @search.to_lon.present?
        the_trips_around_the_requested_day = Trip
                   .unscoped
                   .includes(:points)
                   .where('departure_date >= ?', the_first_date)
                   .where('departure_date <= ?', the_last_date)
                   .where(state: 'confirmed')
                   .to_only(
                      @search.to_lon, @search.to_lat,
                      @search.to_dist
                    )
                   .order(departure_date: :asc)
                   .order(departure_time: :asc)
                   #.page(params[:page]).per(THE_NUMBER_OF_TRIPS_PER_PAGE)
      end
    end

    set__the_previous_trip__departure_date__attribute(the_trips_around_the_requested_day)
    define_the_arrays_of_trips_of_the_selected_day(the_trips_around_the_requested_day)
    define_the_arrays_of_days_and_trips_of_the_past_month(the_trips_around_the_requested_day)
    define_the_arrays_of_days_and_trips_around_the_requested_day(the_trips_around_the_requested_day)
    define_the_trips_per_day_and_the_departure_times_per_day(the_trips_around_the_requested_day)
  end
  
  private
  
    def search_params
      params.permit!
      params[:search] || {}

      # params.require(:search).permit(
      #   :from_city, :from_lon, :from_lat, :from_dist,
      #   :to_city, :to_lon, :to_lat, :to_dist,
      #   :date
      # )
    end
    
    def load_index_meta_data
      # meta data
      @meta[:title] = "#{Rails.application.config.app_name}, rechercher une annonce de covoiturage"
      @meta[:description] = 'Recherchez une annonce de covoiturage parmis toutes les annonces sans frais et faites de la vraie économie du partage, covoiturez gratuitement et librement'
      #@meta[:description] << " de #{search_params[:from_city]}" if search_params[:from_city].present?
      #@meta[:description] << " à #{search_params[:to_city]}"    if search_params[:to_city].present?
      #@meta[:description] << " le #{search_params[:date]}"      if search_params[:date].present?
    end

    def set__the_previous_trip__departure_date__attribute(the_trips_ordered)
      # set .the_previous_trip__departure_date attribute
      if the_trips_ordered.length >= 1
        the_trips_ordered[0].the_previous_trip__departure_date = nil
      end
      if the_trips_ordered.length >= 2
        for a_trip, a_previous_trip in the_trips_ordered[1..-1].zip(the_trips_ordered[0..-2])
          a_trip.the_previous_trip__departure_date = a_previous_trip.departure_date
        end
      end
    end
    
    def define_the_arrays_of_trips_of_the_selected_day(the_trips_ordered)
      # 2 arrays of trips of the selected day (= @search.date_value), all and paginated
      @the_trips_of_the_selected_day__all = the_trips_ordered.select{ |a_trip| a_trip.departure_date == (@search.date_value) }
      @the_trips_of_the_selected_day__paginated = Kaminari.paginate_array(@the_trips_of_the_selected_day__all).page(params[:page]).per(THE_NUMBER_OF_TRIPS_PER_PAGE)
    end
    
    def define_the_arrays_of_days_and_trips_of_the_past_month(the_trips_ordered)
      # trips of the past month (Date.today -31 -> Date.today -1)
      the_trips_of_the_past = the_trips_ordered.select{ |a_trip| a_trip.departure_date < Date.today }
      @the_days_of_the_past_month = *(((Date.today) -THE_NUMBER_OF_DAYS_IN_A_MONTH)..((Date.today) -1))    
      @the_trips_of_the_past_month = the_trips_of_the_past.select{ |a_trip| a_trip.departure_date >= @the_days_of_the_past_month[0] and a_trip.departure_date <= @the_days_of_the_past_month[-1] }
    end

    def define_the_arrays_of_days_and_trips_around_the_requested_day(the_trips_ordered)
      # trips around (@search.date_value) (and >= Date.today) ; (@search.date_value) is supposed to be >= Date.today ; TODO : remove the trips with 0 seat available
      the_trips_of_the_future = the_trips_ordered.select{ |a_trip| a_trip.departure_date >= Date.today }
      @the_days_around_the_requested_day = *(([(Date.today), (@search.date_value) -THE_NUMBER_OF_DAYS_AROUND_THE_REQUESTED_DAY].max)..((@search.date_value) +THE_NUMBER_OF_DAYS_AROUND_THE_REQUESTED_DAY))
      @the_trips_around_the_requested_day = the_trips_of_the_future.select{ |a_trip| a_trip.departure_date >= @the_days_around_the_requested_day[0] and a_trip.departure_date <= @the_days_around_the_requested_day[-1] }
      @the_number_of_days_around_the_requested_day = THE_NUMBER_OF_DAYS_AROUND_THE_REQUESTED_DAY
    end
    
    def define_the_trips_per_day_and_the_departure_times_per_day(the_trips_ordered)
      # trips of per day, and departure times per day
      @the_trips__per_day = {}
      @the_days_around_the_requested_day.each do |a_day|
        the_trips_of_the_current_day = the_trips_ordered.select{ |a_trip| a_trip.departure_date == a_day }
        @the_trips__per_day[a_day] = the_trips_of_the_current_day
      end
      # set of departure time rounded around the clock (13h10 -> 13h, 13h50 -> 13h) of trips of the previous month per day
      @the_departure_times_in_hours__per_day = {}
      @the_trips__per_day.each do |a_day, some_trips|
        the_rounded_departure_times = some_trips.map{ |a_trip| a_trip.departure_time.hour }
        @the_departure_times_in_hours__per_day[a_day] = the_rounded_departure_times.to_set.to_a.sort
      end
    end

end

app/views/search/_form.html.haml
- input_class = large_inputs ? 'input-lg' : ''
- btn_class = large_inputs ? 'btn-lg' : ''

%p Renseignez une ville de départ et/ou une ville d'arrivée.

= simple_form_for @search, url: search_url, method: :get, html: { class: 'form-inline' } do |f|
  = f.input :from_city, as: :string, input_html: { class: "#{input_class} geoname" }, label: false, placeholder: 'De'
  = f.input :from_lon, as: :hidden
  = f.input :from_lat, as: :hidden
  .form-group
    = link_to '<span class="glyphicon glyphicon-transfer" aria-hidden="true"></span>'.html_safe, '#', { class: 'btn btn-default btn-search-inverse-cities' }
  = f.input :to_city, as: :string, input_html: { class: "#{input_class} geoname" }, label: false, placeholder: 'À'
  = f.input :to_lon, as: :hidden
  = f.input :to_lat, as: :hidden
  = f.input :date, as: :string, input_html: { class: "datepicker #{input_class}" }, label: false, placeholder: 'Date'
  .form-group
    = f.button :submit, 'Partez !', class: "btn btn-primary #{btn_class} btn-search"

- content_for :javascript_footer do
  :javascript
    $(".geoname").geonameAutocomplete();

    $(".datepicker").datepicker({
      dateFormat: "DD dd MM yy",
      minDate: 0
    });

    $(".btn-search-inverse-cities").click(function() {
      ["city", "lon", "lat"].forEach(function(fieldName) {
        var $fromInput = $("#search_from_" + fieldName);
        var $toInput = $("#search_to_" + fieldName);

        var fromValue = $fromInput.val();
        $fromInput.val($toInput.val());
        $toInput.val(fromValue);
      });

      return false;
    });

    var lastFocusedInput = $("#search_from_city");
    $("#search_from_city").focusin(function() {
      lastFocusedInput = $("#search_from_city");
    });
    $("#search_to_city").focusin(function() {
      lastFocusedInput = $("#search_to_city");
    });

    $("#new_search").submit(function() {
      var emptyCityGeoCount = 4;
      $(this).find("input.hidden").each(function() {
        var value = $(this).val();
        if (value && value !== "") {
          emptyCityGeoCount -= 1;
        }
      });
      if (emptyCityGeoCount > 2) { // No city fully selected with geo
        var input = lastFocusedInput;

        // Display error
        input.parent().addClass("has-error");
        var inputHelpBlock = input.prev(".help-block");
        if (inputHelpBlock.length > 0) {
          inputHelpBlock.show();
        } else { // Create it
          $("<span>", {
            class: "help-block",
            text: "Sélectionnez une ville dans la liste",
            style: "margin-top: -36px"
          }).insertBefore(input);
        }

        return false; // Prevent submission
      }

      return true;
    });

app/views/search/_not_found.html.haml
There is no trip with such token

app/views/search/index.html.haml
- content_for :search_zone do
  .jumbotron.small-jumbotron{ style: ENV['JUMBOTRON_IMAGE'] ? "background-image: url('#{asset_path(ENV['JUMBOTRON_IMAGE'])}')" : '' }
    .container
      .row
        .col-md-9.col-md-offset-1
          = render partial: 'search/form', locals: { 'large_inputs': false }

%br


%div#the_two_maps
  %div.results_recap 
    -# results recap / errors
    - if (! @search.from_city.blank?) && (! @search.to_city.blank?)
      %p Les trajets <strong>#{@search.from_city} > #{@search.to_city}</strong> (à 25 km près > à 25 km près) : 
    - if  (!  @search.from_city.blank?) && (  @search.to_city.blank?)
      %p Les trajets au départ de <strong>#{@search.from_city}</strong> (à 25 km près), toutes destinations : 
    - if (  @search.from_city.blank?) && (! @search.to_city.blank?)
      %p Les trajets à destination de <strong>#{@search.to_city}</strong> (à 25 km près), toutes origines : 
    - if (  @search.from_city.blank?) && (  @search.to_city.blank?)
      %p Écrivez puis sélectionnez dans la liste : une ville de départ et une ville d'arrivée, ou seulement une ville de départ, ou seulement une ville d'arrivée
    - if (! @search.errors.empty?)
      %p Une ou plusieurs erreurs ont été détectées dans les paramètres de la recherche : #{@search.errors}
  %div#the_trip_start_map
  %div#the_trip_end_map

%div#mini_calendar
  %ul.the_list_of_the_days
    Les trajets à +/- #{@the_number_of_days_around_the_requested_day} jours : 
    - @the_days_around_the_requested_day.each do |a_day|
      - @the_search_parameters_of_the_current_day = {search: {from_city: @search.from_city, from_lon: @search.from_lon, from_lat: @search.from_lat,   to_city: @search.to_city, to_lon: @search.to_lon, to_lat: @search.to_lat,   date: (l a_day, format: :trip_date)}}
      - @the_day_is_on_the_week_end = (a_day.saturday? or a_day.sunday?)
      - @the_day_is_the_selected_day = (a_day == @search.date_value)
      %li.the_day_in_a_list{ class: [(:the_day_without_any_departure if @the_departure_times_in_hours__per_day[a_day].blank?), (:the_day_is_on_the_week_end if @the_day_is_on_the_week_end), (:the_day_is_the_selected_day if @the_day_is_the_selected_day)]}
        = link_to "#{l a_day, format: :trip_date_without_the_year}", search_url(@the_search_parameters_of_the_current_day)
        %ul.the_list_of_the_departure_times
          - @the_departure_times_in_hours__per_day[a_day].each do |a_departure_time_in_hours|
            %li.the_departure_time_in_a_list= "•#{a_departure_time_in_hours}h"

%div
  %div.results_recap 
    %p <strong>#{@the_trips_of_the_selected_day__all.length if @the_trips_of_the_selected_day__all.any?}#{'Aucune' if @the_trips_of_the_selected_day__all.empty?} annonce#{('s' if @the_trips_of_the_selected_day__all.length >= 2)}</strong> pour le #{l (@search.date_value), format: :trip_date}

- if (@the_trips_of_the_selected_day__all.length) > 0
  .row
    .col-md-7.col-md-offset-1
      %h3= "Départ#{('s' if @the_trips_of_the_selected_day__all.length >= 2)} le #{l (@search.date_value), format: :trip_date_without_the_year} : " if (@the_trips_of_the_selected_day__paginated.length) == 0 or (@the_trips_of_the_selected_day__paginated[0].the_previous_trip__departure_date == nil or @the_trips_of_the_selected_day__paginated[0].departure_date != @the_trips_of_the_selected_day__paginated[0].the_previous_trip__departure_date) # the trip is the first trip with this departure date
      %h3= "Départ#{('s' if @the_trips_of_the_selected_day__all.length >= 2)} le #{l (@search.date_value), format: :trip_date_without_the_year} (suite) : " if (@the_trips_of_the_selected_day__paginated.length) > 0 and @the_trips_of_the_selected_day__paginated[0].the_previous_trip__departure_date != nil and @the_trips_of_the_selected_day__paginated[0].departure_date == @the_trips_of_the_selected_day__paginated[0].the_previous_trip__departure_date # the trip is the first of the page and it is not the first trip with this departure date
      .panel.panel-default
        .panel-body{ style: 'padding: 0' }= render @the_trips_of_the_selected_day__paginated
  
  .row
    .col-md-7.col-md-offset-1
      = paginate(@the_trips_of_the_selected_day__paginated)


-# if no results, show what the traveller can do
- if (@the_trips_of_the_selected_day__all.length) == 0
  %div#no_results__show_some_help
    - if @the_trips_of_the_past_month.length >= 1
      %p.help_introduction Pourtant, <em>#{@the_trips_of_the_past_month.length}</em> trajet#{('s' if @the_trips_of_the_past_month.length >= 2)} sur cet itinéraire ont pris la route sur covoiturage-libre.fr le mois dernier.
    %p.help_introduction Tout n'est pas perdu ! <strong>Voilà ce que vous pouvez faire : </strong>
    %ul 
      %li 
        %p.first_help <span class='orange_text'><big>➊</big></span> Augmentez le rayon de recherche (fonctionnalité à venir). 
        %p.second_help Par défaut, le site rabat les trajets passant <span class='orange_text'>25</span> km autour des villes recherchées. 
      %li 
        %p.first_help <span class='orange_text'><big>➋</big></span> Déposez une alerte pour ce trajet (fonctionnalité à venir), 
        %p.second_help vous recevrez un mail dès qu'un conducteur posera l'annonce que vous cherchez. 
      %li 
        %p.first_help <span class='blue_text'><big>➌</big></span> Vous avez une voiture ? Publiez une annonce ! 
        %p.second_help <span class='orange_text'>0</span> passager(s) ont posé une alerte (<- fonctionnalité à venir) et attendent que ce trajet soit proposé. Si vous avez une voiture, proposez ! 
      %li 
        %p.first_help <span class='blue_text'><big>➍</big></span> L'intermodalité : multipliez les moyens de transport !
        %p.second_help En couplant covoiturage avec train ou bus, vous pouvez sûrement trouver une solution. 


- content_for :javascript_footer do
  :javascript
    if (typeof ga === "function") {
      ga('send', 'event', 'Trajet', 'search', '#{[@search.from_city, @search.to_city].join(', ')}', '#{@trips.count}' );
    }
    
    var the_start_coordinates = JSON.parse('#{[@search.from_lat.to_f, @search.from_lon.to_f]}');
    if (the_start_coordinates[0] != '') {
      var the_start_map = L.map('the_trip_start_map').setView(the_start_coordinates, 8);
      
      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '© les contributeurs d\'OpenStreetMap'
      }).addTo(the_start_map);
      L.circle(the_start_coordinates, {radius: 25 *1000}).addTo(the_start_map);
    };
    
    var the_end_coordinates = JSON.parse('#{[@search.to_lat.to_f, @search.to_lon.to_f]}');
    if (the_end_coordinates[0] != '') {
      var the_end_map = L.map('the_trip_end_map').setView(the_end_coordinates, 8);
      
      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
          attribution: '© les contributeurs d\'OpenStreetMap'
      }).addTo(the_end_map);
      L.circle(the_end_coordinates, {radius: 25 *1000}).addTo(the_end_map);
    };