config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    match '/users/finish_signup' => 'users/confirmations#finish_signup', via: [:get, :patch], as: :finish_signup
  end

  devise_for :users, path: 'users', controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions:           'users/sessions',
    registrations:      'users/registrations',
    passwords:          'users/passwords',
    confirmations:      'users/confirmations',
  }

  # translated routes by the route_translator gem
  localized do

    resources :trips, except: [:index, :destroy] do
      member do
        get 'confirm'
        get 'delete'
        get 'resend_confirmation_email'
        get 'resend_information_email'
        get 'new_from_copy'
        get 'new_for_back'
        get 'points'
        get 'phone_number_image'
        get 'confirm_delete'
      end
      resource :phone, only: :show, controller: 'trips/phones'
      resources :messages
    end
    get 'search', to: 'search#index'
    get 'profile', to: 'profile#show', as: 'profile'
    get 'profile/trips', to: 'profile#trips', as: 'profile_trips'
    get 'profile/alerts', to: 'profile#alerts', as: 'profile_alerts'
    get 'profile/edit', to: 'profile#edit', as: 'edit_profile'
    patch 'profile', to: 'profile#update'

    get "/covoits/:from-:to", to: 'landing#index'
    # get "/covoits/:from", to: 'landing#index'
    resources :user_alerts, except: [:index]
  end

  resources :cities, defaults: { format: :json } do
    collection do
      get 'autocomplete'
      get 'main'
    end
  end

  namespace :admin do
    resources :users do
      put :lock
      delete :lock, to: 'users#unlock'
      post :send_reset_password_mail
      post :send_confirmation_mail
    end
    resources :page_parts
    resources :pages
    resources :stats, only: :index do
      collection do
        get 'trips_count'
        get 'trips_tab'
      end
    end
    root to: 'pages#index'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get "/:id", to: 'pages#show'

  root to: 'home#index'
end

app/models/cms/page_part.rb
class Cms::PagePart < ApplicationRecord

  self.table_name = 'cms_page_parts'

  validates_presence_of :name

end

app/controllers/admin/page_parts_controller.rb
class Admin::PagePartsController < AdminController

  before_action :load_page_part, only: [:show, :edit, :update, :delete]

  def index
    @page_parts = Cms::PagePart.all
  end

  def show
  end

  def new
    @page_part = Cms::PagePart.new
  end

  def create
    @page_part = Cms::PagePart.new(page_part_params)
    if @page_part.save
      redirect_to admin_page_parts_url, notice: 'Contenu créé avec succès.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @page_part.update_attributes(page_part_params)
      redirect_to admin_page_parts_url, notice: 'Les modifications ont bien été enregisrées.'
    else
      render :edit
    end
  end

  def delete
    @page_part.destroy
    redirect_to admin_page_parts_url, notice: 'Le contenu a bien été supprimé.'
  end

  private

    def load_page_part
      @page_part = Cms::PagePart.find(params[:id])
    end

    def page_part_params
      params.require(:page_part).permit(:id, :name, :title, :body)
    end

end

app/views/admin/page_parts/_form.html.haml
- url = @page_part.new_record? ? admin_page_parts_path : admin_page_part_path(@page_part)
- method = @page_part.new_record? ? :post : :put

.row
  .col-md-5.col-md-offset-3.well
    = simple_form_for @page_part, as: :page_part, url: url, method: method do |f|
      = f.input :id
      = f.input :name
      = f.input :title
      = f.input :body

      .pull-right
        = link_to 'Annuler', admin_page_parts_path, class: 'btn btn-default'
        = f.button :submit, class: 'btn-primary'

app/views/admin/page_parts/edit.html.haml
%h1 Édition du "Page Part"

= render 'form'

app/views/admin/page_parts/index.html.haml
%h1.pull-left Liste des "Page Parts"

= link_to 'Nouveau "Page part"', new_admin_page_part_path, class: 'btn btn-primary pull-right top-list-button'

%table.table
  %tr
    %th Id
    %th Nom
    %th Titre
    %th Corps
    %th{ colspan: 2 }
  - @page_parts.each do |page_part|
    %tr
      %td= page_part.id
      %td= page_part.name
      %td= page_part.title
      %td= page_part.body
      %td= link_to 'Edit', edit_admin_page_part_path(page_part), class: 'btn btn-default btn-sm'

app/views/admin/page_parts/new.html.haml
%h1 Nouveau "Page Part"

= render 'form'