config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    match '/users/finish_signup' => 'users/confirmations#finish_signup', via: [:get, :patch], as: :finish_signup
  end

  devise_for :users, path: 'users', controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions:           'users/sessions',
    registrations:      'users/registrations',
    passwords:          'users/passwords',
    confirmations:      'users/confirmations',
  }

  # translated routes by the route_translator gem
  localized do

    resources :trips, except: [:index, :destroy] do
      member do
        get 'confirm'
        get 'delete'
        get 'resend_confirmation_email'
        get 'resend_information_email'
        get 'new_from_copy'
        get 'new_for_back'
        get 'points'
        get 'phone_number_image'
        get 'confirm_delete'
      end
      resource :phone, only: :show, controller: 'trips/phones'
      resources :messages
    end
    get 'search', to: 'search#index'
    get 'profile', to: 'profile#show', as: 'profile'
    get 'profile/trips', to: 'profile#trips', as: 'profile_trips'
    get 'profile/alerts', to: 'profile#alerts', as: 'profile_alerts'
    get 'profile/edit', to: 'profile#edit', as: 'edit_profile'
    patch 'profile', to: 'profile#update'

    get "/covoits/:from-:to", to: 'landing#index'
    # get "/covoits/:from", to: 'landing#index'
    resources :user_alerts, except: [:index]
  end

  resources :cities, defaults: { format: :json } do
    collection do
      get 'autocomplete'
      get 'main'
    end
  end

  namespace :admin do
    resources :users do
      put :lock
      delete :lock, to: 'users#unlock'
      post :send_reset_password_mail
      post :send_confirmation_mail
    end
    resources :page_parts
    resources :pages
    resources :stats, only: :index do
      collection do
        get 'trips_count'
        get 'trips_tab'
      end
    end
    root to: 'pages#index'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get "/:id", to: 'pages#show'

  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # cms data
    @page_part_1 = Cms::PagePart.where(id: 1)

    @search = Search.new

    # TODO: dynami
    @cities = [
      'Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg',
      'Montpellier', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Le Have',
      'Saint-Étienne', 'Toulon', 'Grenoble', 'Dijon', 'Angers', 'Nîmes',
      'Villeurbanne', 'Le Mans', 'Clermond-Ferrand', 'Aix-en-Provence',
      'Brest', 'Limoges', 'Tours', 'Amiens', 'Perpignan', 'Metz',
      'Boulogne-Billancourt'
    ]

    @repeated_trips = Trip.confirmed.repeated.latests.limit(5)
    @unrepeated_trips = Trip.incoming.confirmed.unrepeated.orphans.soon.limit(5)
    @latest_trips = Trip.incoming.confirmed.latests.limit(5)
    @incoming_trips = Trip.incoming.confirmed.soon.limit(5)

    @testimonials = [
      {
        author: {
          name: 'Kévin HEYDENS',
          avatar_url: 'default-avatar.png'
        },
        published_at: '23/08/2016',
        body: 'Bravo pour votre association, vive la solidarité et la communauté libre !'
      },
      {
        author: {
          name: 'Michel VIN',
          avatar_url: 'default-avatar.png'
        },
        published_at: '13/08/2016',
        body: 'Bravo pour cette initiative qui va me permettre de proposer des trajets à frais partagés en covoiturage avec mon véhicule de collection (Ford T) et en particulier des tours sur le remblai de La Baule'
      },
      {
        author: {
          name: 'Émilie HILLEREAU',
          avatar_url: 'default-avatar.png'
        },
        published_at: '08/08/2016',
        body: 'Ravie de participer au développement du VRAI covoiturage qui me manque tant… Vive le covoiturage LIBRE !'
      }
    ]
  end

end

app/views/home/_banner.html.haml
.p-home__banner.alert.alert-info.mb-0
  .container
    .row
      .col-sm-12
        %button.home__banner_close.glyphicon.glyphicon-remove-circle
        = image_tag 'lilo-blue.png', alt: 'Lilo', class: 'home__banner_logo'
        %h3.p-home__heading Chères utilisatrices et chers utilisateurs,
        %p
          Covoiturage-libre.fr est un service gratuit porté par une association à but non lucratif. <strong>Grâce au moteur de recherche Lilo, vous pouvez nous financer sans bourse délier</strong> en nous donnant les <em>gouttes d'eau</em> que vous gagnez à chaque recherche.
        %p
          Merci pour votre soutien&nbsp;!
    .row
      .col-sm-12
        = link_to 'Découvrir le moteur de recherche Lilo', 'https://www.lilo.org/?utm_source=covoiturage-libre-fr', target: '_blank', rel: 'noopener', class: 'btn btn-default'
        = link_to 'Déjà sur Lilo ? Donnez-nous vos gouttes !', 'https://www.lilo.org/?p=9680&utm_source=covoiturage-libre-fr', target: '_blank', rel: 'noopener', class: 'btn btn-default'

- content_for :javascript_footer do
  :javascript
    // Close button for banner
    var banner = $(".p-home__banner");
    var banner_close = $(".home__banner_close");
    banner_close.on("click", function() {
      banner_close.hide();
      banner.animate({height: 0}, 500, function() {
        // Animation complete.
        banner.hide();
      });
    });

app/views/home/index.html.haml
- # meta data
- @meta[:title] = 'Covoiturage-libre.fr, le covoiturage gratuit et collaboratif'
- @meta[:description] = '1ère plateforme de covoiturage gratuite et collaborative. Aucune commission sur les trajets. Association à but non lucratif. Depuis 2011.'

- content_for :page_part_1 do
  .container
    .row
      .col-sm-12
        = @page_part_1.try(:body)

- content_for :search_zone do
  .jumbotron{ style: ENV['JUMBOTRON_IMAGE'] ? "background-image: url('#{asset_path(ENV['JUMBOTRON_IMAGE'])}')" : '' }
    .container
      .row
        .col-md-9
          %h1.p-home__title Le covoiturage gratuit, collaboratif et libre.
          %h2.p-home__subtitle Trouvez votre covoiturage
          = render partial: 'search/form', locals: { 'large_inputs': true }
        .col-md-3
          .home-publish-cta
            %p.home-publish-cta__title
              Vous avez une voiture&nbsp;?
            = link_to 'Publiez une annonce', new_trip_path, class: 'btn btn-lg btn-primary', id: 'new_trip_button'
            %p
              Le site ne prend aucune commission
              %br
              Association loi 1901

- content_for :home_content do
  = render 'banner'
  %section.p-home__features
    .container
      .row
        .col-sm-4
          %h3.p-home__heading Sans commission
          %p
            Des économies plus importantes pour les conducteurs, des voyages vraiment moins chers pour les passagers. Les prix sont fixés par les conducteurs, le site ne prélève aucune commission sur les trajets, nous ne vivons que de dons.
          %p
            = link_to 'Faire un don »', 'https://www.helloasso.com/associations/covoiturage-libre-fr/collectes/campagne-courante/', target: '_blank', rel: 'noopener', class: 'btn btn-default'
        .col-sm-4
          %h3.p-home__heading Libre
          %p Nous avons pris cinq engagements :
          %ul
            %li la plateforme est un bien commun : nous ne serons jamais achetés ou cotés en bourse ;
            %li nous ne vivons que de dons : il n'y a pas de commission sur les trajets ;
            %li la gouvernance de la plateforme est fondée sur la communauté ;
            %li notre communauté contribue à la protection de l'environnement ;
            %li la plateforme contribue au lien social entre covoitureurs.
          %p
            = link_to 'Pour en savoir plus »', '/association', class: 'btn btn-default'
        .col-sm-4
          %h3.p-home__heading Un bien commun
          %p
            Le covoiturage est un bien commun : la valeur créée par les utilisateurs en covoiturant, comme conducteurs ou comme passagers, doit revenir aux utilisateurs.
            La plateforme est animée et développée par des bénévoles. Pour améliorer la plateforme, la faire mieux connaître, bref, contribuer activement, c'est ici.
          %p
            = link_to 'Contribuer »', '/missions-benevoles', class: 'btn btn-default'

  -#%section.p-home__cities
  -#  .container
  -#    .row
  -#      .col-sm-12
  -#        %h3.p-home__heading Trajets au départ de :
  -#        %ul.l-home__cities
  -#          - @cities.each do |city|
  -#            %li.l-home__city
  -#              = link_to city, '#', class: 'c-link'
  -#        = link_to 'Tous les trajets en cours »', '#', class: 'p-home__all-trips c-link'

  %section.p-home__testimonials
    .container
      .row
        .col-sm-8
          %h3.p-home__heading Les usagers en parlent
          %ul.c-testimonials
            - @testimonials.each do |testimonial|
              = render 'shared/testimonial', testimonial: testimonial
          -# link_to 'Lire plus de commentaires >', '#', class: 'c-link c-testimonial__link-more'

        .col-sm-4
          %h3 Recevez nos fameux stickers
          .c-stickers-carousel
            = link_to 'https://www.helloasso.com/associations/covoiturage-libre-fr/collectes/campagne-courante/', { target: '_blank', rel: 'noopener', class: 'c-stickers-carousel__slides' } do
              - 3.times do |index|
                .c-stickers-carousel__item
                  = image_tag "sticker-#{index + 1}.jpg"
            .c-stickers-carousel__controls
              %button.c-stickers-carousel__control.js-carousel-left
                = image_tag 'carousel-arrow.png'
              %span{id: 'active-sticker'}
              \/ 3
              %button.c-stickers-carousel__control.js-carousel-right
                = image_tag 'carousel-arrow.png'